/*
 * Int-App Application API
 *
 * Lorem ipsum
 *
 * OpenAPI spec version: 1.0.0
 * Contact: daniel.leslie@apivista.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RequestIntakeApplication : IEquatable<RequestIntakeApplication>
    { 
        /// <summary>
        /// Gets or Sets QuestionAndAnswer
        /// </summary>
        [DataMember(Name="questionAndAnswer")]
        public List<QuestionAndAnswer> QuestionAndAnswer { get; set; }

        /// <summary>
        /// Gets or Sets Applicant
        /// </summary>
        [DataMember(Name="applicant")]
        public Object Applicant { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestIntakeApplication {\n");
            sb.Append("  QuestionAndAnswer: ").Append(QuestionAndAnswer).Append("\n");
            sb.Append("  Applicant: ").Append(Applicant).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RequestIntakeApplication)obj);
        }

        /// <summary>
        /// Returns true if RequestIntakeApplication instances are equal
        /// </summary>
        /// <param name="other">Instance of RequestIntakeApplication to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestIntakeApplication other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    QuestionAndAnswer == other.QuestionAndAnswer ||
                    QuestionAndAnswer != null &&
                    QuestionAndAnswer.SequenceEqual(other.QuestionAndAnswer)
                ) && 
                (
                    Applicant == other.Applicant ||
                    Applicant != null &&
                    Applicant.Equals(other.Applicant)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (QuestionAndAnswer != null)
                    hashCode = hashCode * 59 + QuestionAndAnswer.GetHashCode();
                    if (Applicant != null)
                    hashCode = hashCode * 59 + Applicant.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RequestIntakeApplication left, RequestIntakeApplication right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RequestIntakeApplication left, RequestIntakeApplication right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
