/*
 * Int-App Application API
 *
 * Lorem ipsum
 *
 * OpenAPI spec version: 1.0.0
 * Contact: daniel.leslie@apivista.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Primitives;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Models;
using Utilities.EventHubUtility;

using Microsoft.Azure.EventHubs;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class ApplicationsApiController : Controller
    { 
        /// <summary>
        /// Push a new application to the event queue
        /// </summary>
        
        /// <param name="body">Application to be added</param>
        /// <response code="201">Application Sent</response>
        /// <response code="405">Invalid input</response>
        [HttpPost]
        [Route("/v1/applications")]
        [ValidateModelState]
        [SwaggerOperation("AddApplication")]
        [SwaggerResponse(statusCode: 201, type: typeof(string), description: "Application Sent")]
        public async virtual Task<IActionResult> AddApplication([FromBody]RequestIntakeApplication body)
        { 

            var bodyContent = body.ToJson();
            try {
                await EventHubUtility.CreateEventHub(bodyContent);
            } catch {
                
            }

            string JsonResponse = null;
            JsonResponse = "\"\"";
            
            var Response = JsonResponse != null
            ? JsonConvert.DeserializeObject<string>(JsonResponse)
            : default(string);
            return new ObjectResult("");
        }
    }
}
